### ISSUE TITLE
Continous stream

### ISSUE THREAD

**Issue by xCausxn** [phaux/node-ffmpeg-stream#1]
Hey there,

I saw your library and was wondering if it would be possible to stream to a RTMP server from an empty pipe.

Basically making the stream stay connected, and then when data is added to the pipe stream that content.

Or stream a static image as a intermission.

Kind Regards,
xCausxn

**Comment by phaux** [comment]
You can turn your main stream into series of jpeg images with output format `mjpeg` and combine it with static image by repeatedly piping a single jpeg image when there's no data from main stream.
Then pipe it to second ffmpeg process which combines jpeg images into video.

I didn't test it, but you can start with this:

```js
var fs = require('fs')
  , ffmpeg = require('ffmpeg-stream').ffmpeg

// the combining ffmpeg process
var combine = ffmpeg()
  , combineInput = combine.input({ f: 'mjpeg' })

// remember if we are streaming currently
var streaming = false

// argument should be a WebM video stream
function streamVideo(stream) {

	streaming = true

	// the splitting ffmpeg process
	var split = ffmpeg()

	// pipe video to splitting process
	stream.pipe(split.input({ f: 'webm' }))

	// get jpegs and pipe them to combining process
	split.output({ f: 'mjpeg' }).pipe(combineInput, { end: false })

	stream.on('end', function() {

		// video stream ended
		streaming = false

	})

	split.run()

}

setInterval(function() {

	// if we are not streaming...
	if (!streaming) {

		// pipe a single jpeg file 30 times per second
		// into the combining process
		fs.createReadStream('intermission_pic.jpg')
		.pipe(combineInput, { end: false })

	}

}, 1000 / 30)

// the final output
combine.output({ f: 'whatever format you want' }).pipe(/* wherever you want */)

combine.run()
```

**Comment by jamescauson** [comment]
Awesome thanks for the reply its much appreciated :D I will give this a test run when im home form work :D
