### ISSUE TITLE
Specific not work "start" FILE FOR VIDEO

### ISSUE THREAD

**Issue by codiac82** [phaux/node-ffmpeg-stream#2]
I have 70 gigabytes of video and I'll extract a fragment of a size of 10 megabytes
Example:
1. fs.createReadStream('sample.txt', {start: 50 000 000, end: 60 000 000})
2.res.writeHead(206, {
'Content-disposition': 'filename=streamxx.mp4',
'Accept-Ranges': 'bytes',
'Content-Type': "video/mp4",
'Content-Range': 'bytes ' + start + '-' + end + '/' + GridFile.length,//GridFile.length, // start = 50 000 000
'Content-Length': chunksize
});
3. GridFile.seek(start, function () { // start = 50 000 000
or Other

These examples can extract part of the video file, but can not play in this part of the HTML5 Video tag . I tried FFMPEG and its superstructure but still can not play. As this fragmetn play or what or how to modify it ??

**Comment by phaux** [comment]
I don't see how is it related to this library or ffmpeg in general.

**Comment by codiac82** [comment]
Then it is pointless to discuss any further.


---------- Původní zpráva ----------

Od: phaux <notifications@github.com>

Komu: phaux/node-ffmpeg-stream <node-ffmpeg-stream@noreply.github.com>

Datum: 6. 5. 2016 16:23:49

Předmět: Re: [phaux/node-ffmpeg-stream] Specific not work "start" FILE FOR 
VIDEO (#2)


"

I don't see how is it related to this library or ffmpeg in general.

—

You are receiving this because you authored the thread.

Reply to this email directly or view it on GitHub
(https://github.com/phaux/node-ffmpeg-stream/issues/2#issuecomment-217453645)






"=
