### ISSUE TITLE
Example with intermidate Stream

### ISSUE THREAD

**Issue by SNRSE** [phaux/node-ffmpeg-stream#22]
Hey , i saw the example with the Stream and an intermisson Image. How could I add audio ? also does it change the quality ?

**Comment by phaux** [comment]
You can have 2 input streams. One with video frames as JPEG, and one with frame-length chunks of audio data.

**Comment by SNRSE** [comment]
so the workflow would be : a NGIX-RMTP server where it accepts the streams that then get converter into jpegs and audio snippets which are then again added together ? wouldn't it then also be problem when the stream crashes that the audio is missing and the final output will fail ?. 
Can I use any other format for the buffer ?

**Comment by phaux** [comment]
Use this if you want more control:

https://github.com/Streampunk/beamcoder
