### ISSUE TITLE
Impossible to specify multiple map parameters

### ISSUE THREAD

**Issue by JoshuaWalsh** [phaux/node-ffmpeg-stream#25]
First, thanks for this great library. I'm finding it pleasant to work with.

With ffmpeg it is often necessary to add multiple `map` options. For example, to combined the video from one file with the audio from another.

The ffmpeg command I need to specify looks something like this:

```bash
ffmpeg -i video.mkv -i audio.mkv -map 0:v -map 1:a output.mp4
```

I'm trying to do something like:

```typescript
const ffmpeg = new Converter();
ffmpeg.createInputFromFile(videoFile, {});
ffmpeg.createInputFromFile(audioFile, {});
const stream = ffmpeg.createOutputStream({
    map: '0:v',
    map: '1:a',
});
ffmpeg.run();
```

But it doesn't work because a JavaScript object is not able to contain the same key more than once.

(This example is simplified. My real code involves `filter_complex`, but for simplicity I have omitted it.)

My suggestion is for options to accept array values in addition to string values. If an array is passed, that option will be emitted multiple times, once for each value in the array. I'm happy to submit a PR for this if you're happy with the idea.

Thanks!

**Comment by phaux** [comment]
That's a great idea. I don't know why I didn't think of this in the first place.

**Comment by JoshuaWalsh** [comment]
I'll submit a PR in the next few days.
