### ISSUE TITLE
Create a single audio / video stream using MediaStreamRecorder and Node.js

### ISSUE THREAD

**Issue by SalvatoreAD** [phaux/node-ffmpeg-stream#3]
My webapp records the participants of video conference every 60 seconds and do the upload to the server using this function (I'm using another plugin (socket.io-stream) . 

Server-side

```
ss(socket).on("file:add:stream", function(stream, data, roomId) {
    console.log(stream);
    var dataStream = fs.createWriteStream('./public/uploads/' + roomId + "/" + data + ".webm", {
        'flags': 'a',
        'encoding': 'base64'
    });

    stream.pipe(dataStream, {
        end: false
    });

    stream.on('end', function() {
        ss(socket).emit('file:add:stream:success');
    });
});
```

Client side

```
var stream = ss.createStream({
            highWaterMark: 384000,
            allowHalfOpen: true
        });
        stream.forceBase64 = true;
        ss(socket).emit('file:add:stream', stream, blob.streamid, roomId, blob.size);
        var blobReadStream = ss.createBlobReadStream(blob, {highWaterMark: 384000});
        blobReadStream.pipe(stream, {end: false});
        ss(socket).on('file:add:stream:success', function(data) {
            console.info('file uploaded to server');
        });
```

Whenever I concatenate the buffers arriving, the video saved (webm format) is played badly and out of sync.

How can I fix the problem with this plugin?

**Comment by phaux** [comment]
1. Is the client code running in browser or node.js?
2. Where does the client get the video stream from?

**Comment by SalvatoreAD** [comment]
1. The client is on the browser2. Videos are recorded using mediastreamrecorder and with OnDataAvailable () function proceeds the blob and I upload using the method above.-------- Messaggio originale --------Oggetto: Re: [phaux/node-ffmpeg-stream] Create a single audio / video stream using MediaStreamRecorder and Node.js (#3)Da: phaux A: phaux/node-ffmpeg-stream CC: SalvatoreAD ,Author 
Is the client code running in browser or node.js?
Where does the client get the video stream from?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/phaux/node-ffmpeg-stream","title":"phaux/node-ffmpeg-stream","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/phaux/node-ffmpeg-stream"}},"updates":{"snippets":[{"icon":"PERSON","message":"@phaux in #3: 1. Is the client code running in browser or node.js?\r\n2. Where does the client get the video stream from?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/phaux/node-ffmpeg-stream/issues/3#issuecomment-266808268"}}}

**Comment by phaux** [comment]
With this lib you can mix the streams as they are sent instead of using temporary file as you do now, but it won't help with the out-of-sync problem.

If you recorded the time when every client joined and then delay their stream in the final mixed stream appropiately there shouldn't be any problem.

The best solution would be to use WebRTC and make the server act as a peer in the meeting, but that's non-trivial.

**Comment by SalvatoreAD** [comment]
Can you help me to create the server-side code and client-side code for browser? if I can create a better video files in my lib, it would be of great help. If you want I'll give you an email

**Comment by phaux** [comment]
No

**Comment by SalvatoreAD** [comment]
I have difficulty to use your lib. Thanks anyway
