### ISSUE TITLE
Question regarding the '-framerate' argument

### ISSUE THREAD

**Issue by olastor** [phaux/node-ffmpeg-stream#30]
I am trying to rebuild the following command which should display the image for 10 seconds in the output video. Later it should be used for multiple images:

`ffmpeg -framerate 0.1 -i https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Sossusvlei%2C_Namibia%2C_2018-08-06%2C_DD_017.jpg/916px-Sossusvlei%2C_Namibia%2C_2018-08-06%2C_DD_017.jpg\?download -c:v libx264  -r 30 -pix_fmt yuv420p test.mp4`

Using the following code it does not show any errors, but the `-framerate 0.1` seems to not be applied as the output video is not 10 seconds long (player opens it, but ends immediately).

```
const { Converter } = require("ffmpeg-stream")
const fs = require('fs');

const frames = ["image.png"] // any image from file for now.

const converter = new Converter()

// create input writable stream
const input = converter.createInputStream({ framerate: 0.1, f: "image2pipe", r: 30 })

// output to file
converter.createOutputToFile("out.mp4", {
  vcodec: "libx264",
  pix_fmt: "yuv420p"
})

// for every frame create a function that returns a promise
frames
  .map(frame => () =>
    new Promise((resolve, reject) =>
      fs.createReadStream(frame)
        .on("end", resolve)
        .on("error", reject)
        .pipe(input, { end: false })
    )
  )
  // reduce into a single promise, run sequentially
  .reduce((prev, next) => prev.then(next), Promise.resolve())
  // end converter input
  .then(() => input.end())

converter.run().then(() => console.log('DONE'))
```

Thanks for any advice!

**Comment by phaux** [comment]
framerate should be argument to output stream, not input stream

**Comment by olastor** [comment]
okay, thanks
