### ISSUE TITLE
Stream Output Doesn't Work, But File Output Does

### ISSUE THREAD

**Issue by Pecacheu** [phaux/node-ffmpeg-stream#4]
I'm trying to convert H.264 (or other format) files to H.265 + MP3. I'm on Windows, so I already have an HVEC codec, and I downloaded ffmpeg.exe and set `process.env.FFMPEG_PATH` to the path. The library works fine if I specify the filename in `converter.output`, but I'm going to stream the data over the network, so I need a stream.

This is my code:
```
const converter = ffmpeg();

converter.input(__dirname+'/testH264.mp4');

//Video Quality (crf) 0->40, Audio Quality (aq) 0->10
converter.output({
	f:'mp4', vcodec:'hevc', acodec:'mp3', crf:25, aq:4,
	vf:'scale='+SCREEN_W+':'+SCREEN_H+':force_original_'+
	'aspect_ratio=increase,crop='+SCREEN_W+':'+SCREEN_H,
	vframes:400
}).pipe(fs.createWriteStream(__dirname+'/testH265.mp4'));
converter.run();
```
Here's the error:
```
<... Irrelevant Stuff ...>
  [mp4 @ 0000000000e4db00] muxer does not support non seekable output
  Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
  Error initializing output stream 0:1 --
  encoded 0 frames
  Conversion failed!

    at ChildProcess.<anonymous> (<DirPath>\node_modules\ffmpeg-stream\lib\ffmpeg.js:215:27)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by phaux** [comment]
ffmpeg says that the combination of options you specified doesn't support streaming. You can experiment with calling ffmpeg directly and specifying `-` as output file. Maybe some other options or different format will work. Streaming sequence of JPEGs over websockets worked flawlessly for me (`f: 'mjpeg'`).

You can specify the magic option `conv.output({buffer: true, ...opts})`. That tells the library to save output to a temporary file and then create a node stream from that file. It wont start producing data until the conversion is complete, though.

> I downloaded ffmpeg.exe and set `process.env.FFMPEG_PATH` to the path.

better idea would be to run your program as `env FFMPEG_PATH=... npm start` (or windows equivalent) every time to decouple ffmpeg install location from the program logic. You can also put ffmpeg into system32 directory.

**Comment by phaux** [comment]
I added the solution to the FAQ in README. Closing.
