### ISSUE TITLE
Creating video from multiple file buffers

### ISSUE THREAD

**Issue by dushyantbangal** [phaux/node-ffmpeg-stream#5]
I have images in Amazon S3 bucket (private) so I'm using their SDK to download those. I get the files in `Buffer` objects. Is there any way I can use your package to create a video out of it?

So far I've been downloading the files and then using the following command:
`ffmpeg -framerate 30 -pattern_type glob -i '*.jpg' -c:v libx264 -pix_fmt yuv420p out.mp4`

But now want to do it from my node js application automatically.

**Comment by phaux** [comment]
```js
const frames = ['frame1.jpg', 'frame2.jpg', ...]

const conv = ffmpeg() // create converter
const input = conv.input({f: 'image2pipe', r: 30}) // create input writable stream
conv.output('out.mp4', {vcodec: 'libx264', pix_fmt: 'yuv420p'}) // output to file

// for every frame create a function that returns a promise
frames.map(filename => () =>
  new Promise((fulfill, reject) =>
    s3
      .getObject({Bucket: '...', Key: filename})
      .createReadStream()
      .on('end', fulfill) // fulfill promise on frame end
      .on('error', reject) // reject promise on error
      .pipe(input, {end: false}) // pipe to converter, but don't end the input yet
  )
)
// reduce into a single promise, run sequentially
.reduce((prev, next) => prev.then(next), Promise.resolve())
// end converter input
.then(() => input.end())
```

;)

[AWS docs](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/requests-using-stream-objects.html)

**Comment by dushyantbangal** [comment]
Its throwing me timeout.
When I try with `.pipe(process.stdout)`, the `end` event gets called for each frame.
But when I'm doing `.pipe(input, {end: false})`, `error` event gets called.

**Comment by dushyantbangal** [comment]
I created a separate code with this and it doesn't throw any error, but the file is not created either.

When integrated in my server, I get `write after end` error after some time along with `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: Connection timed out after 120000ms` which I think is from S3

**Comment by dushyantbangal** [comment]
ok, got it!
`conv.run()` did the thing!

**Comment by phaux** [comment]
I knew I forgot something :x

**Comment by stagadish** [comment]
Hey @phaux ,
how would you modify this if you didn't have to request the images from an AWS S3 service and instead they were available locally?
I am trying the following, but without much luck:

```
var ffmpeg = require('ffmpeg-stream').ffmpeg;
var fs = require('fs');
const conv = ffmpeg();

const frames = ['frame1.jpg', 'frame2.jpg', ...];

const input = conv.input({ f:'image2pipe', r: 30 });
conv.output( 'out.mp4', { vcodec: 'libx264', pix_fmt: 'yuv420p' });

frames.map(filename => () =>
    new Promise((fulfill, reject) =>
        fs.
        createReadStream(filename)     //<--- here's the main difference
        .on('end', fulfill)
        .on('error', reject)
        .pipe(input, {end: false})
    )
)
.reduce((prev, next) => prev.then(next), Promise.resolve())
.then(() => input.end())
```
There's just no output file coming out, and I am uncertain of out to debug this (somewhat new to js and node.js).

Thanks!

**Comment by stagadish** [comment]
Sheesh.
It was the `conv.run()` thing again *facepalm*.
It works now.

**Comment by cantuket** [comment]
Hey @phaux,

Thanks for putting this module together!

Not sure if you can help, but I'm getting some extremely strange results when trying to upload the output to S3. I've uploaded many other mp4s created from ffmpeg in the same way without an issue so I'm guessing this has to do with the encoding settings or incorrect ContentType or ContentEncoding on S3 upload?

1) My program outputs mp4 at 5.2mb, plays fine on my machine.
2) Upload through aws-sdk, and file becomes 2.6mb and wont play/corrupted
3) Upload same video manually through S3 GUI and works fine, comes out to 5.2mb.

My code is very similar to the above with some minor variations, but if you're aware of options to fix this or at least point me in the right direction I would greatly appreciate it.

```
const conv = ffmpeg() 
        const input = conv.input({f: 'image2pipe', r: 10})
        conv.output(tmpFile, {vcodec: 'libx264', pix_fmt: 'yuv420p', vframes: 100})

        imgRun.map(({Key}) => () =>
            new Promise((fulfill, reject) =>
                s3
                .getObject({Bucket: 'some-bucket', Key})
                .createReadStream()
                .on('end', fulfill) 
                .on('error', reject) 
                .pipe(input, {end: false}) 
            )
        )
        .reduce((prev, next) => prev.then(next), Promise.resolve())
        .then(() => {
            input.end()
            resolve(tmpFile)
        })

        conv.run()
```

Uploading to S3 with 'ContentType: video/mp4'

**Comment by phaux** [comment]
@cantuket `conv.run()` returns a promise which resolves on ffmpeg process exit.

**Comment by Firiyuu** [comment]
How to get this through a link?

**Comment by yecandir** [comment]
I am just curious about can we add stream from already decoded images 

For example:

const input = conv.input({ f:'image2pipe', r: 30, i:'-'});
conv.output( 'out.mp4', { vcodec: 'libx264', pix_fmt: 'yuv420p' });

frames.map(data => () =>
    new Promise((fulfill, reject) =>

//??????????????????????
        fs.createReadStream(Buffer.from(data))    //create read stream from Buffer
//?????????????????????
        .on('end', fulfill)
        .on('error', reject)
        .pipe(input, {end: false})
    )
)
.reduce((prev, next) => prev.then(next), Promise.resolve())
.then(() => input.end())

It does not accepting it

**Comment by phaux** [comment]
@yecandir 

```js
const converter = new Converter()
const converterInput = converter.createInputStream({ ...options })
for (const buffer of imageBuffers) {
  converterInput.write(buffer)
}
```

**Comment by Afaq-Javed** [comment]
Hi,

I'm new to this thing and want to convert the rtsp live stream into img's is their a way i can do that using this package.

Thank you.
