### ISSUE TITLE
Rewrite in JS

### ISSUE THREAD

**Issue by phaux** [phaux/node-ffmpeg-stream#6]
CoffeeScript is obsolete.

- [ ] rewrite in modern JS line-to-line
- [ ] replace usage of bluebird with async functions

**Comment by dushyantbangal** [comment]
Any specific reason you haven't used any of the following?

http://js2.coffee/
https://github.com/decaffeinate/decaffeinate

**Comment by phaux** [comment]
Decaffeinate looks cool

**Comment by phaux** [comment]
Fixed by #13
