### ISSUE TITLE
Is there a "Process completed" event?

### ISSUE THREAD

**Issue by dushyantbangal** [phaux/node-ffmpeg-stream#7]
I need to know when the video conversion is completed.
I was not able to find any example for it.

Also, is there a way to get some sort of live progress, or atleast whatever messages `ffmpeg` CLI tool prints?

**Comment by phaux** [comment]
> I need to know when the video conversion is completed.

```js
converter.run()
  .then(() => console.log(`Conversion completed`))
  .catch(err => console.error(`Conversion failed: ${err}`))
```

> Also, is there a way to get some sort of live progress, or atleast whatever messages ffmpeg CLI tool prints?

Currently no
